Part 1 - Numpy

Use this dataset for the first 4 questions.

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

In [1]:
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


1.⁠ ⁠Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.


In [2]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([3, 4, 5, 6, 7])

vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A.reshape(-1,1), B.reshape(-1,1)))
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Vertical Stack:
 [[1 2 3 4 5]
 [3 4 5 6 7]]
Horizontal Stack:
 [[1 3]
 [2 4]
 [3 5]
 [4 6]
 [5 7]]


2.⁠ ⁠Find common elements between A and B. [Hint : Intersection of two sets]

In [3]:
common_elements = np.intersect1d(A, B)
print("Common Elements:", common_elements)

Common Elements: [3 4 5]


3.⁠ ⁠Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]

In [4]:
filtered_A = A[(A > 5) & (A < 10)]
print("Filtered A:", filtered_A)

Filtered A: []


4.⁠ ⁠Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [5]:
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]
print("Filtered Iris Data:\n", filtered_iris)

Filtered Iris Data:
 [[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Part 2 - Pandas

1.⁠ ⁠From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [7]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
every_20th_row = df.iloc[::20, [0, 1, 2]]
print("Filtered Data (Every 20th Row):\n", every_20th_row)

Filtered Data (Every 20th Row):
    Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


2.⁠ ⁠Replace missing values in Min.Price and Max.Price columns with their respective mean.

df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [8]:
df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
df['Max.Price'].fillna(df['Max.Price'].mean(), inplace=True)
print("Updated DataFrame with Mean for Missing Values in Min.Price and Max.Price:")
print(df[['Min.Price', 'Max.Price']].head())

Updated DataFrame with Mean for Missing Values in Min.Price and Max.Price:
   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


<ipython-input-8-ec247b2dbd09>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Min.Price'].fillna(df['Min.Price'].mean(), inplace=True)
<ipython-input-8-ec247b2dbd09>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)'

3.⁠ ⁠How to get the rows of a dataframe with row sum > 100?

df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [9]:
df_random = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
filtered_rows = df_random[df_random.sum(axis=1) > 100]
print("Rows with Sum > 100:\n", filtered_rows)

Rows with Sum > 100:
      0   1   2   3
1   28  36  14  28
2   10  33  36  39
4   24  37  24  16
6   38  19  28  31
9   33  25  37  17
10  31  18  29  31
13  26  27  29  19
14  13  22  34  32
